### ISSUE TITLE
bug in go defer

### ISSUE THREAD

**Issue by stremovsky** [mosuka/cete#4]
You have same bug in a LOT of places. For example in kvs/raft_server.go .
The order is not correct. In case of error, **client** variable is **nil**:

		client, err := NewGRPCClient(string(node.GrpcAddr))
		defer func() {
			err := client.Close()
			if err != nil {
				s.logger.Printf("[ERR] %v", err)
			}
		}()
		if err != nil {
			s.logger.Printf("[ERR] %v", err)
			return nil
		}

Here you do it correctly: **cmd/cete/cluster.go** and other places

	client, err := kvs.NewGRPCClient(grpcAddr)
	if err != nil {
		return err
	}
	defer func() {
		err := client.Close()
		if err != nil {
			_, err = fmt.Fprintln(os.Stderr, err)
		}
	}()

In NewGRPCClient() function in case of error you return nil object and and error. Here is relevant code:

func NewGRPCClient(address string) (*GRPCClient, error) {

        .........
	conn, err := grpc.DialContext(ctx, address, dialOpts...)
	if err != nil {
		cancel()
		return **nil**, err
	}

**Comment by mosuka** [comment]
@stremovsky Thanks for the reporting. I'll change it next version.

**Comment by stremovsky** [comment]
When you are planning to release next version?

**Comment by mosuka** [comment]
@stremovsky Sorry, I closed the issue by mistake.
Next week I'll fix the indicated code and release v0.1.1.
Thanks.

**Comment by stremovsky** [comment]
Thanks!

**Comment by mosuka** [comment]
@stremovsky 
I've released v0.1.1.
Thanks!
