### ISSUE TITLE
Will cete support distributed transaction?

### ISSUE THREAD

**Issue by gezerui0124** [mosuka/cete#51]
As a distributed KV store, I think distributed transaction is needed.
Will cete implement this?

**Comment by gezerui0124** [comment]
I think the key of distributed db is partition, so splitting all keys into key ranges is important.
Meanwhile, you can do many things just like shard.
But it indeed increase the complexity as it requires more components, just like place driver...

**Comment by mosuka** [comment]
Hi @rayzui ,
Unfortunately, there are currently no plans to support distributed transactions. It would be nice to be able to implement it someday, but it seems to be a long way off.

**Comment by gezerui0124** [comment]
Noted with thanks!
